name: Sexy Time
main: me.cheeseballs500.SexyTime.SexyIce
version: 1.4 beta
description: Placing obsidian makes an entity call sexy woman (HOT)

commands:
  opi:
    description: Makes you NOT attracted to Sexy Women
  run:
    description: trolololololol
  runas:
    description: trolololololol
  sudo:
    description: trolololololol
  deopi:
    description: Makes you re-attracted to Sexy Women
  broadcasti:
    description: Says stuff